- file/retro_dirent.c
- include/retro_dirent.h
- include/retro_stat.h
- lists/dir_list.c
retro_dirent and retro_stat tidy and bugfixes: windows retro_dir would have missed the first entry; retro_stat wasn't extern "C"'d; retro_dirent_is_dir didn't need a path argument (path can always be gotten from RDIR in a trivial operation)
> retro_dirent and retro_stat tidy and bugfixes

- include/string/stdstring.h
- string/stdstring.c
It just iterates over the string and capitalizes each character following a space, then capitalizes the very first character of the string.
I don't know how changes made to this repo are merged with RetroArch's `libretro-common` folder as it doesn't seem to be a submodule.
> (stdstring.c) Added string_ucwords to capitalize first letter of each word

- glsm/glsm.c
All of that information gets "overwritten" anyway when glsm_state_bind runs, so there is no need to "0" it all out during the unbind. (tested and working)
> There is no need to make the GPU do this work

- include/glsym/rglgen_headers.h
gl3ext.h exists, so it should be used
> This causes compile errors

- glsym/glgen.py
- glsym/glsym_es2.c
- glsym/rglgen.py
- include/glsym/glsym_es2.h
EXT extensions are currently excluded in the glgen.py script.
I need to use this extension:
https://www.khronos.org/registry/gles/extensions/EXT/EXT_discard_framebuffer.txt
Which is present on any Android phone I know of, and the Raspberry Pi.
This change is a result of removing EXT from the list of excluded extensions and running glgen.py on a laptop with Mesa.
This has been tested on Android (GLES2 and GLES3), Raspberry Pi, and a laptop with Intel Mesa Graphics.
EXT extensions are different from OES extensions in that they aren't written by the Khronos Group, they are typically written by companies (I believe EXT_discard_framebuffer was written by Apple). However, some of these extensions, like EXT_discard_framebuffer, are pretty universal, and are used by many different vendors.
> Add EXT extensions to GLES2 headers

- libco/armeabi.c
The function "crash" was defined in this file, but never used. I removed the function to prevent warnings when using this file.
> libco/armeabi.c: Remove unused function

- conversion/float_to_s16_neon.c
- conversion/s16_to_float_neon.c
Add ARM thumb compatibility as a '.c' version of following assembler files: float_to_s16_neon and s16_to_float_neon
> Add ARM thumb compatibility (-mthumb)

- glsym/glgen.py
- glsym/glsym_es2.c
- include/glsym/glsym_es2.h
This GLint64/GLuint64 stuff in the GLES2 headers has caused nothing but problems. They are only used by glGetQueryObjecti64vEXT and glGetQueryObjectui64vEXT, which no cores that I know of use.
I still have compilation issues with GLES2 and GLupeN64, so I propose just getting rid of these items from the GLES2 code (GLES3+ is unaffected)
> Fix GLES2 compile

- include/encodings/crc32.h
- include/encodings/utf.h
- include/file/archive_file.h
- include/file/config_file_userdata.h
- include/file/nbio.h
- include/formats/jsonsax.h
- include/gfx/gl_capabilities.h
- include/gfx/math/matrix_3x3.h
- include/gfx/math/vector_2.h
- include/gfx/math/vector_4.h
- include/gfx/scaler/pixconv.h
- include/gfx/scaler/scaler_int.h
This is just some work to clean up the libretro-common libraries. Needed for my libretro_loader.exe. 
Still a work in progress.
> Add missing guards to headers.

- rthreads/rthreads.c
Using high performance counters instead of timegettime and begintimeperiod
This has two main advantages:
- It is supported in UWP apps in addition to desktop apps
- It is more efficient than the old way of getting timestamps
> WinRT compilation fix

- include/streams/file_stream_transforms.h
Those warnings will appear when a define for those functions already exists : VITA, WiiU, Android (32bits), ...
> Fix to avoid redefined warnings

- rthreads/rthreads.c
GetCurrentThread() is useless, it returns a pseudo-handle which is the same value in every thread, or something like that, rendering isself nonfunctional. the thread ID is more useful.
> win32 - fix bug in sthread_isself

- include/libretro.h
Given the common occurrence of additional buttons on modern mice, I propose adding controls RETRO_DEVICE_ID_MOUSE_BUTTON_4 and RETRO_DEVICE_ID_MOUSE_BUTTON_5 to the set of constants. 
Sega Saturn cores can map these to the required start button input on its official mouse, to more accurately represent the real hardware. Other cores, such as for ports of Doom and Quake would also benefit.
> Add constants for mouse buttons 4&5

- include/libretro.h
Added support for analog buttons. Cores can use the new libretro.h constant to request analog input from any RetroPad button. Use the following reference implementation to maintain compatibility with older front-ends.
```
static uint16_t get_analog_button( retro_input_state_t input_state_cb,
int player_index,
int id )
{
uint16_t button;
// NOTE: Not all front-ends support analog buttons (or pre-date it) 
// so we need to handle this in a graceful way.
// First, try and get an analog value using the new libretro API constant
button = input_state_cb( player_index,
RETRO_DEVICE_ANALOG,
RETRO_DEVICE_INDEX_ANALOG_BUTTON,
id );
if ( button == 0 )
{
// If we got exactly zero, we're either not pressing the button, or the front-end
// is not reporting analog values. We need to do a second check …
```
> Analog buttons

- audio/dsp_filters/ChipTuneEnhance.dsp
- audio/dsp_filters/Makefile
- audio/resampler/drivers/sinc_resampler_neon.S
- glsym/glgen.py
- glsym/rglgen.py
- samples/utils/Makefile
- streams/file_stream.c
- vfs/vfs_implementation.c
This was accomplished with this command.
```
find . -type f -not -iwholename '*.git*' -exec sed -i 's/[ \t]*$//' {} \;
```
Given that libretro-common could end up in other repos I thought it would be good to remove these trailing white spaces at the source. Surprisingly there weren't very many of them.
> Remove trailing white space.

- audio/dsp_filters/reverb.c
Rewrote the reverb model to take into account different samplerates.
This is needed because the original model was written with 44.1khz in mind, which is a design flaw.
The comb and allpass filters are now changed to have proper computed reverb coefficients.
This is needed for "accurate" reverb with systems with lower or greater than 44.1khz.
Such as the SNES, GBA and others.
> Rewrite reverb DSP to take into account input samplerate.

- include/file/file_path.h
I find myself usually needing the slash as a char.
As things are I can use`path_default_slash()[0]` but I wondered if having a character version might be useful.
> add character versions of path_default_slash

- include/libretro.h
Based on this existing language I falsely concluded that I would not be able to set core options again from within the core code once I had set them for the first time and `retro_run` was going.
This language I believe more accurately reflects how the API works but please correct any of my misunderstandings. The warning about changing the number of core options comes from https://github.com/libretro/RetroArch/issues/6371
Thanks also to radius for educating me on this
> clarify that core options may be set by the core again

- audio/audio_mixer.c
- include/audio/audio_mixer.h
This adds *.flac decoding to libretro-common's audio mixer.
This also supports OggFlac decoding too.
Requires dr_flac.h
> Add FLAC decoding.

- file/file_path.c
According to the docs/comment, path_remove_extension should return the "path with the extension part removed."
Currently this function is returning the extension itself, rather than the path.
> fix return of path_remove_extension

- file/file_path.c
This is how things currently work:
* If `path_remove_extension` is provided a path with an extension such as `/storage/game.zip`, it returns `/storage/game` -- the expected behavior
* if `path_remove_extension` is provided a path that already has no extension such as `/storage/game` it returns `NULL` -- not what I was expecting
This PR changes the outcome of the second scenario so that it also returns `/storage/game`. I believe this is also more consistent with the behavior of other functions in this library.
> path_remove_extension should return original path when there is no extension

- include/libretro.h
Thank you for considering my recent PRs to libretro-common.
This update, like others, isn't not coming from a theoretical basis but rather as an attempt to make sure we're handling a real life situation where the "save" folder is set to NULL correctly.
If this updated text is accurate, I hope that maybe it can anticipate this question about the save folder before someone else asks it all over again.
> update description of the "save" directory

- file/file_path.c
- include/file/file_path.h
The important correction is that if the `path` string has no extension, then `path_remove_extension()` **does not** return "a pointer to the unaltered original path" as the docs currently say.
In that case  `path_remove_extension()` returns `NULL`.
> correct path_remove_extension docs

- include/libretro.h
Some of the RETRO_ENVIRONMENT_ values were scattered and the list was out of numerical order.
> Sort #define RETRO_ENVIRONMENT_ values and keep them in one place.

- include/streams/file_stream_transforms.h
- streams/file_stream_transforms.c
I used `rfprintf` as a base, because arguments were the same
> Fix fscanf drop-in replacement

- include/glsym/glsym.h
So, with the yabasanshiro libretro core, i can't use glsm on android without adding some definition to glsm.
The first idea was to apply this patch : https://pastebin.com/raw/gGuYwbnz , however it would end up disappearing if someone decided to regenerate those files
The second idea was to generate `glsym_es31.h` and `glsym_es31.c` by running glgen.py on `GLES3/gl31.h`, but the generated files didn't end up well (i had to tinker with them to build the core, and when it finally built, it crashed)
That's why i came up with this third solution : it allows the developper to add his own gl symbol by simply defining `HAVE_GLSYM_PRIVATE` and having a file named `glsym_private.h` in the include dirs, it works well, is flexible, and is less intrusive than the other solutions.
As a proof of concept …
> Allow "private" gl symbol loader

- include/libretro.h
I have been reading in #programming that this callback is no longer recommended. If that's the case I suggest indicating it in the comments.
> indicate that GET_OVERSCAN is not recommended

- include/glsm/glsm.h
- include/glsm/glsmsym.h
- include/rthreads/rthreads.h
- rthreads/rthreads.c
Removing GLdouble seems right, until a more proper fix is found i recommend using the `HAVE_GLSYM_PRIVATE` stuff to handle the issue on a per-target basis when device's gles implementation is missing it (see https://github.com/libretro/flycast/blob/master/core/libretro/glsym_private.h)
> backport stuff from flycast

- include/glsm/glsm.h
Build won't fail if we sync those typedef with the ones from Khronos headers
> proper fix for the GLdouble issue

- streams/file_stream.c
`int filestream_getc(RFILE *stream)` would
- return 0 if `stream` is `NULL` but also when a 0 byte is read
- if `char` is `signed`, potentially return `EOF` when reading a byte with the same value (typically -1)
Which means that error/`EOF` checking will have false positives.
This also affects `filestream_gets` and `filestream_getline` as they use `filestream_getc`.
`int filestream_putc(RFILE *stream, int c)` has the same issue of returning negative written bytes.
This PR changes both functions to be more in line with the C analogs [fgetc](https://en.cppreference.com/w/c/io/fgetc) and [fputc](https://en.cppreference.com/w/c/io/fputc), i.e.
- return `EOF` in any error case
- return written bytes as an `unsigned char`
> fix filestream_getc and filestream_putc semantics

- include/libretro.h
- samples/core_options/README.md
- samples/core_options/example_default/libretro_core_options.h
- samples/core_options/example_hide_option/libretro_core_options.h
- samples/core_options/example_translation/libretro_core_options.h
As more and more cores receive 'enhanced option' updates, we're seeing more and more copy/paste errors caused by copying `libretro_core_options.h` files from one repo to another...
This PR adds some standard example/template `libretro_core_options.h` files which can be used as a general reference for core devs. These will be updated as any future API changes are made.
This PR also clarifies a couple of API comment in `libretro.h`
> Add sample libretro_core_options.h files

- include/libretro.h
- samples/core_options/example_default/libretro_core_options.h
- samples/core_options/example_hide_option/libretro_core_options.h
- samples/core_options/example_translation/libretro_core_options.h
Following developer feedback, this PR makes some very slight changes to v1 core options API reference comments, and to the provided `libretro_core_options.h` examples:
- In `libretro.h`, comments have been updated to reflect the fact that the core options v1 interface should be supported if `RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION` is >= 1 (previously, the comments indicated that core options v1 would only be supported if `RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION` == 1)
- In `libretro.h`, and explanation of the `RETRO_NUM_CORE_OPTION_VALUES_MAX` define is provided (at least one dev has queried this)
- The `libretro_core_options.h` samples now include a 'version' header comment, including a changelog (so we can keep track of updates)
- The `libretro_core_options.h` samples now use the …
> Core options updates/clarifications

- include/libretro.h
- samples/core_options/README.md
- samples/core_options/example_default/libretro_core_options.h
- samples/core_options/example_default/libretro_core_options_intl.h
- samples/core_options/example_hide_option/libretro_core_options.h
- samples/core_options/example_hide_option/libretro_core_options_intl.h
- samples/core_options/example_translation/libretro_core_options.h
- samples/core_options/example_translation/libretro_core_options_intl.h
This PR updates the core option definition samples to v1.3:
- Translations have been moved to `libretro_core_options_intl.h`
- `libretro_core_options_intl.h` contains a BOM marker + UTF-8 build fix for MSVC 2010-2013
- A new `HAVE_NO_LANGEXTRA` define flag is used to disable translations (enabling c89 builds, which are incompatible with `libretro_core_options_intl.h` due to the BOM marker)
> Update 'libretro_core_options.h' samples to v1.3

- include/libretro.h
I just noticed that the core options comments in `libretro.h` have been reverted again (this time by commit 670db5112445f53e2129bc647c911d771c465a98)
This PR fixes them again.
> (libretro.h) Fix core options comments

- include/libretro.h
This resolves #129 and should leave room for future RETROK_* values
> increase max number of core options to 192

- include/retro_common_api.h
It's not clear whether `__STDC_FORMAT_MACROS`  can already be defined as an empty macro, or as 1. This results in compilation warning on some platforms (mingw under Linux for example.)
Only define it if not already defined, and define it to 1 instead of as an empty macro.
> Fix warnings about redefining __STDC_FORMAT_MACROS

- glsym/glgen.py
- glsym/rglgen.py
- glsym/xglgen.py
Python convention expects a single main docstring per file.
> Single docstring for license

- include/libretro.h
This PR just updates `libretro.h` to the latest version, with the additions required for the v1 disk control interface API.
(Also included are the correct up-to-date comments for core options v1)
> Update libretro.h (disk control interface v1)

- include/retro_endianness.h
Those macros reference the parameter multiple times, so
if it has any side effects, like incrementing, then the
code gets screwed. Even worse: number of increments depends on
endianness.
This uses inline functions in the same way as they were already used in
this file.
> retro_endianness: Replace swap macros with inline functions

- formats/m3u/m3u_file.c
- include/formats/m3u_file.h
- include/streams/rzip_stream.h
- streams/rzip_stream.c
This PR adds the new `rzip_stream` interface code. This is required since it is referenced in the recently updated `interface_stream` code (https://github.com/libretro/libretro-common/commit/48848f66f1822efa772dc5dd11f28e648736436d, https://github.com/libretro/libretro-common/commit/d23277f2b0798a7bbb710b7cdc83c0d55d94f61d)
The new `m3u_file` code is also added (seemed appropriate to do this here, since it is also file-related)
> Add 'rzip_stream' and 'm3u_file' libraries

- file/file_path.c
On the file path function **path_relative_to**, given two paths that share a common beginning but differ on a directory where both share the first characters, the resulting relative path is wrong because it's trimming too much of the original path. For example:
> * path:  
> **/home/johanbcn/retroarch-old**/shaders/shaders_glsl/crt/shaders/crt-cgwg-fast.glsl
> * base:  
> **/home/johanbcn/retroarch**/shaders/
> * output:  
> **../../-old**/shaders/shaders_glsl/crt/shaders/crt-cgwg-fast.glsl
This pull request fixes this behavior; the following examples were tested:
> * path:  
> **/home/johanbcn/retroarch-old**/shaders/shaders_glsl/crt/shaders/crt-cgwg-fast.glsl
> * base:  
> **/home/johanbcn/retroarch**/shaders/
> * previous output:  
> …
> Prevent path_relative_to function from trimming too many characters

- libco/armeabi.c
Without this we end up trying to execute thumb code as arm which results
in a crash
> Mark co_switch_arm as thumb function when using thumb

- features/features_cpu.c
This is to match pending PRs on Retroarch side
> cpu_features_get_time_usec: Improve on djgpp, psp and vita

- vfs/vfs_implementation_cdrom.c
filestream_scanf needs this to work properly with real cd, and Kronos core relies on this function
> (cdrom) read shouldn't return 0 for cue when len is too big

- file/archive_file.c
- file/archive_file_7z.c
- file/archive_file_zlib.c
- include/file/archive_file.h
Avoid returning a pointer onto the stack from `zip_parse_file_iterate_step` and `sevenzip_parse_file_iterate_step`.
The pointer onto the stack was used after `archive_parse_file_iterate_step` returned, after `file_archive_parse_file_iterate` returned, inside `file_archive_get_file_crc32`.
This moves the array containing the filename into the archive_extract_userdata struct instead of storing a pointer there.
This PR also renames the member from `extracted_file_path` to `current_file_path` and removes the unused `archive_name` array from the archive_extract_userdata struct. The name `extracted_file_path` wasn't really correct as it is also used during iteration/walking over the archive.
I searched through all of github for "extracted_file_path" and through some front-end projects for …
> Avoid returning a pointer onto the stack from zip_parse_file_iterate_step

- file/nbio/nbio_stdio.c
- vfs/vfs_implementation.c
Use fseeko/ftello not _fseeki64/_ftelli64 in MinGW builds
On MinGW, _fseeki64/_ftelli64 can have broken behavior depending on the number of opened file handles.
> Use fseeko/ftello not _fseeki64/_ftelli64 in MinGW builds

- include/compat/msvc.h
According to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l only starting in MSVC 2015 vsnprintf complies with the C99 standard. Before that, vsnprintf was available but did not NULL terminate a string that got filled up. This would lead to program crashes with overflowing strings. Tested on MSVC 2013.
Relevant excerpts from the documentation:
> When using _vsnprintf and _vsnwprintf, the buffer will be null-terminated only if there's room at the end
> Beginning with the UCRT in Visual Studio 2015 and Windows 10, vsnprintf is no longer identical to _vsnprintf. The vsnprintf function complies with the C99 standard.
> Fix vsnprintf between MSVC 2008 and 2013

- include/rthreads/rthreads.h
- rthreads/rthreads.c
This comes from https://github.com/TASVideos/desmume/pull/367
I don’t have any Windows to test things on, so I only implemented it for pthread for now.
> Add a helper function to set thread name in rthread

- include/rthreads/rthreads.h
- rthreads/rthreads.c
Reverts libretro/libretro-common#167
> Revert "Add a helper function to set thread name in rthread"

- compat/compat_snprintf.c
According to the C standard, vsnprintf should accept a 0 length size parameter.
Without this fix, the following code crashes the program:
```c
snprintf(NULL, 0, "");
```
One feature of the function is to measure the bytes needed to encode a format string is by calling it with such a  `NULL, 0` pair. 
While a format of "" might not be a realistic usage of snprintf, something like `("%s", str)` or `("%*.s", count, "")` is.
The relevant C standard excerpt:
>    The snprintf function is equivalent to fprintf, except that the output is
>    written into an array (specified by argument s) rather than to a stream. If
>    n is zero, nothing is written, and s may be a null pointer. Otherwise,
>    output characters beyond the n-1st are discarded rather than being written
>    to the array, and a …
> Fix MSVC pre-2015 vsnprintf crash

- net/net_ifinfo.c
get correct size from GetAdaptersAddresses
> net_ifinfo: crashfix  (Windows)

- formats/json/rjson.c
Remove unnecessary variable assignment as suggested/warned by Xcode
'Although the value stored to 'from' is used in the enclosing expression, the value is never actually read from 'from''
> rjson: Fix duplicated variable assign (Xcode suggestion)

- gfx/scaler/pixconv.c
This file wouldn't build when using Unreal Engine's Android toolchain. 
I think the intended behavior was to short-circuit when `_MSC_VER` isn't defined which I've modified it to do.
> Fix undefined macro causing build to fail on some platforms

- include/compat/zlib.h
- include/compat/zlib/zlib.h
commit d9ee8e3ec1dca2b6d1a9bc3c71d56ef6f0d23ef0 broke uncompr.c compilation because of uncompress() declaration and definition type missmatch
> fix uncompr.c compilation

- audio/audio_mixer.c
audio_mixer_play_ogg calls stb_vorbis_close if types.ogg.stream is set
but it overlaps with wav.position and stb_vorbis_close ends up freeing
unallocated space and crashing
Space saving is minor, so let's just split the variants
> Replace union with struct in audio_mixer_voice

- audio/audio_mixer.c
It's sometimes NULL. Most likely because load and decode are done separately
and so it may be loaded but not even decoded yet
@twinaphex
> Add guard for empty ogg stream

- features/features_cpu.c
I'm compiling a project for RISC-V 64-bit that depends on `libretro-common`, and I got errors:
```
../desmume/desmume/src/libretro-common/features/features_cpu.c:321:31: error: ‘AT_HWCAP’ undeclared (first use in this function)
321 |    uint64_t hwcap = getauxval(AT_HWCAP);
|                               ^~~~~~~~
../desmume/desmume/src/libretro-common/features/features_cpu.c:321:31: note: each undeclared identifier is reported only once for each function it appears in
../desmume/desmume/src/libretro-common/features/features_cpu.c:323:23: error: ‘HWCAP_ARM_NEON’ undeclared (first use in this function)
323 |       return (hwcap & HWCAP_ARM_NEON) != 0;
|                       ^~~~~~~~~~~~~~
../desmume/desmume/src/libretro-common/features/features_cpu.c:325:23: error: ‘HWCAP_ARM_VFPv3’ …
```
> Detect `ARM` rather than exclude `x86` for `ARM` specific code

- features/features_cpu.c
Reverts libretro/libretro-common#200
> Revert "Detect `ARM` rather than exclude `x86` for `ARM` specific code"

- rthreads/rthreads.c
this is to cover all platforms where struct timeval is used
> rthreads: include sys/time.h for mips and 3ds

- audio/dsp_filters/reverb.c
Based on updated reverb model in foo_dsp_effect. Thought I would backport it.
Might work on more things like early reflections and other things as I backport from WTFweg and foo_dsp_effect. Upgrading to a feedback delay network would be nicer than plain Schroeder-Moorer.
Possible improvements could be SSE/NEON optimization but I guess thats down the line once I get a M1 Mac for WTFweg.
> Add proper stereo seperation in reverb.

- rthreads/tpool.c
This is for handling a rare case when all threads are free without any work (working_cnt == 0) but there exist some work items that are not yet done or not yet started to be processed.
I'm using your code (first I took it from your blog) in my program. It was very useful. However I noticed that when I use 1 or 2 threads the pool thread will finish without any doing any job.I'm calling `tpool_wait` right after adding all works (I had only one or two work items to add for that specific example) so the function, `tpool_wait`, locks the mutex prior to any working thread takes the mutex. In that case `(!tm->stop && tm->working_cnt != 0)` is false so it will not call `pthread_cond_wait(&(tm->working_cond), &(tm->work_mutex))` and exit immediately. Then I call `tpool_destroy` right after that …
> Wait until there is any work item to be done

- streams/trans_stream_zlib.c
Reading `*.gz` files was already possible by supplying a fitting `windows_bits` of 31 for instance.
https://www.zlib.net/manual.html
> windowBits can also be greater than 15 for optional gzip encoding. Add 16 to windowBits to write a simple gzip header and trailer around the compressed data instead of a zlib wrapper. The gzip header will have no file name, no extra data, no comment, no modification time (set to zero), no header crc, and the operating system will be set to the appropriate value, if the operating system was determined at compile time. If a gzip stream is being written, strm->adler is a CRC-32 instead of an Adler-32.
For compression it is also possible to write a gzip header:
> windowBits can also be greater than 15 for optional gzip decoding. Add 32 to windowBits to enable …
> Add support for writing gzip files in trans_stream_zlib

- rthreads/ctr_pthread.h
considering to use rthreads in pcsx_rearmed
> add apparent missing includes in ctr_pthread
